### ISSUE TITLE
Issue with Save-HTMLReport

### ISSUE THREAD

**Issue by bbevard** [azurefieldnotes/ReportHTML#6]
In the latest code base you define $ReportContent as an array, which the variable is, but for some reason when executing it that way, I get a PoSH error that I can't pass an empty variable.  Commenting out the variable casting fixes it and everything executes fine.  Maybe it is me trying to do stuff at 6:30am before I have finished my first coffee, but I just wanted to let you know.

**Comment by mquickenden** [comment]
I have reviewed and made some changes to the save-htmlreport, although I haven't removed the array type.  It does seem to work.  If you could test 1.3.0.4, latest code uploaded on GitHub that would be good before I upload the module to powershell gallery.
